# Generated by Django 2.0.5 on 2018-08-06 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='filenya',
            field=models.FileField(upload_to='dokumen/%Y/%m/%d/', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
